language: node_js
node_js:
 - "8"

os:
 - linux  

install:
- npm install

if: branch = master

stages:
 - test
 - deploy

jobs:
 include:
   - stage: test
     name: test
     script: npm run test
   - stage: deploy
     name: deploy
     script:
       - echo "NPM Deploying Started ..."
       - npm version
       - echo "NPM Building Finished."
     deploy:
       provider: npm
       email: chenfengjw@hotmail.com
       api_key: "$NPM_TOKEN"
       skip_cleanup: true
       on:
         tags: true
