language : node_js
node_js:
 - "8"


os:
 - linux

install:
- npm install

if: branch = master

stages:
 - name: test
 - name: deploy

jobs:
 include:
   - stage: test
    name: test
    script: npm run test
   - stage: deploy
     deploy:
       provider: npm
       email: chenfengjw@hotmail.com
       api_key: "$NPM_TOKEN"
       skip_cleanup: true
       on:
         tags: true
